/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;

@SuppressWarnings("all")
public interface RemoteProxyProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RemoteProxyProtocol\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"types\":[{\"type\":\"enum\",\"name\":\"State\",\"symbols\":[\"IDLE\",\"WORKING\",\"BUSY\"]},{\"type\":\"enum\",\"name\":\"Command\",\"symbols\":[\"SAVE_FILE\",\"INFO\",\"GET_FILE\",\"RUN_TASK\"]},{\"type\":\"record\",\"name\":\"NodeState\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"state\",\"type\":\"State\"}]},{\"type\":\"record\",\"name\":\"Task\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"command\",\"type\":\"Command\"},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]},{\"type\":\"record\",\"name\":\"InfoRecord\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"data\",\"type\":\"string\"}]}],\"messages\":{\"pullPendingTasks\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"Task\"}},\"ping\":{\"request\":[{\"name\":\"state\",\"type\":\"NodeState\"}],\"response\":\"null\"},\"pushNodeInfo\":{\"request\":[{\"name\":\"info\",\"type\":\"InfoRecord\"}],\"response\":\"null\"},\"pushCompletedTask\":{\"request\":[{\"name\":\"task\",\"type\":\"Task\"}],\"response\":\"null\"}}}");
  java.util.List<br.unb.cic.bionimbus.avro.proto.Task> pullPendingTasks() throws org.apache.avro.AvroRemoteException;
  java.lang.Void ping(br.unb.cic.bionimbus.avro.proto.NodeState state) throws org.apache.avro.AvroRemoteException;
  java.lang.Void pushNodeInfo(br.unb.cic.bionimbus.avro.proto.InfoRecord info) throws org.apache.avro.AvroRemoteException;
  java.lang.Void pushCompletedTask(br.unb.cic.bionimbus.avro.proto.Task task) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends RemoteProxyProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = br.unb.cic.bionimbus.avro.proto.RemoteProxyProtocol.PROTOCOL;
    void pullPendingTasks(org.apache.avro.ipc.Callback<java.util.List<br.unb.cic.bionimbus.avro.proto.Task>> callback) throws java.io.IOException;
    void ping(br.unb.cic.bionimbus.avro.proto.NodeState state, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void pushNodeInfo(br.unb.cic.bionimbus.avro.proto.InfoRecord info, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void pushCompletedTask(br.unb.cic.bionimbus.avro.proto.Task task, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}