/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;  
@SuppressWarnings("all")
public enum State { 
  IDLE, WORKING, BUSY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"symbols\":[\"IDLE\",\"WORKING\",\"BUSY\"]}");
}
