/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;  
@SuppressWarnings("all")
public class Task extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Task\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"command\",\"type\":{\"type\":\"enum\",\"name\":\"Command\",\"symbols\":[\"SAVE_FILE\",\"INFO\",\"GET_FILE\",\"RUN_TASK\"]}},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  @Deprecated public long id;
  @Deprecated public br.unb.cic.bionimbus.avro.proto.Command command;
  @Deprecated public java.util.List<java.lang.CharSequence> data;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return command;
    case 2: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: command = (br.unb.cic.bionimbus.avro.proto.Command)value$; break;
    case 2: data = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'command' field.
   */
  public br.unb.cic.bionimbus.avro.proto.Command getCommand() {
    return command;
  }

  /**
   * Sets the value of the 'command' field.
   * @param value the value to set.
   */
  public void setCommand(br.unb.cic.bionimbus.avro.proto.Command value) {
    this.command = value;
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.util.List<java.lang.CharSequence> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.List<java.lang.CharSequence> value) {
    this.data = value;
  }

  /** Creates a new Task RecordBuilder */
  public static br.unb.cic.bionimbus.avro.proto.Task.Builder newBuilder() {
    return new br.unb.cic.bionimbus.avro.proto.Task.Builder();
  }
  
  /** Creates a new Task RecordBuilder by copying an existing Builder */
  public static br.unb.cic.bionimbus.avro.proto.Task.Builder newBuilder(br.unb.cic.bionimbus.avro.proto.Task.Builder other) {
    return new br.unb.cic.bionimbus.avro.proto.Task.Builder(other);
  }
  
  /** Creates a new Task RecordBuilder by copying an existing Task instance */
  public static br.unb.cic.bionimbus.avro.proto.Task.Builder newBuilder(br.unb.cic.bionimbus.avro.proto.Task other) {
    return new br.unb.cic.bionimbus.avro.proto.Task.Builder(other);
  }
  
  /**
   * RecordBuilder for Task instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Task>
    implements org.apache.avro.data.RecordBuilder<Task> {

    private long id;
    private br.unb.cic.bionimbus.avro.proto.Command command;
    private java.util.List<java.lang.CharSequence> data;

    /** Creates a new Builder */
    private Builder() {
      super(br.unb.cic.bionimbus.avro.proto.Task.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(br.unb.cic.bionimbus.avro.proto.Task.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Task instance */
    private Builder(br.unb.cic.bionimbus.avro.proto.Task other) {
            super(br.unb.cic.bionimbus.avro.proto.Task.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = (java.lang.Long) data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.command)) {
        this.command = (br.unb.cic.bionimbus.avro.proto.Command) data().deepCopy(fields()[1].schema(), other.command);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'command' field */
    public br.unb.cic.bionimbus.avro.proto.Command getCommand() {
      return command;
    }
    
    /** Sets the value of the 'command' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder setCommand(br.unb.cic.bionimbus.avro.proto.Command value) {
      validate(fields()[1], value);
      this.command = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'command' field has been set */
    public boolean hasCommand() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'command' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder clearCommand() {
      command = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'data' field */
    public java.util.List<java.lang.CharSequence> getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder setData(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.data = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'data' field */
    public br.unb.cic.bionimbus.avro.proto.Task.Builder clearData() {
      data = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Task build() {
      try {
        Task record = new Task();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.command = fieldSetFlags()[1] ? this.command : (br.unb.cic.bionimbus.avro.proto.Command) defaultValue(fields()[1]);
        record.data = fieldSetFlags()[2] ? this.data : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
