// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protomessage.proto

package br.biofoco.p2p.protocol.protobuf;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // required .protocol.protobuf.ProtoMessage.Command command = 2;
    boolean hasCommand();
    br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command getCommand();
    
    // required .protocol.protobuf.ProtoMessage.MessageType type = 3;
    boolean hasType();
    br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType getType();
    
    // required string srcId = 4;
    boolean hasSrcId();
    String getSrcId();
    
    // required string dstId = 5;
    boolean hasDstId();
    String getDstId();
    
    // repeated string argument = 6;
    java.util.List<String> getArgumentList();
    int getArgumentCount();
    String getArgument(int index);
  }
  public static final class ProtoMessage extends
      com.google.protobuf.GeneratedMessage
      implements ProtoMessageOrBuilder {
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(Builder builder) {
      super(builder);
    }
    private ProtoMessage(boolean noInit) {}
    
    private static final ProtoMessage defaultInstance;
    public static ProtoMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.biofoco.p2p.protocol.protobuf.MessageProtos.internal_static_protocol_protobuf_ProtoMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.biofoco.p2p.protocol.protobuf.MessageProtos.internal_static_protocol_protobuf_ProtoMessage_fieldAccessorTable;
    }
    
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      PING(0, 1),
      STORE(1, 2),
      FIND_NODE(2, 3),
      FIND_VALUE(3, 4),
      ;
      
      public static final int PING_VALUE = 1;
      public static final int STORE_VALUE = 2;
      public static final int FIND_NODE_VALUE = 3;
      public static final int FIND_VALUE_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Command valueOf(int value) {
        switch (value) {
          case 1: return PING;
          case 2: return STORE;
          case 3: return FIND_NODE;
          case 4: return FIND_VALUE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Command[] VALUES = {
        PING, STORE, FIND_NODE, FIND_VALUE, 
      };
      
      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Command(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.protobuf.ProtoMessage.Command)
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      REQUEST(0, 1),
      RESPONSE(1, 2),
      ;
      
      public static final int REQUEST_VALUE = 1;
      public static final int RESPONSE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return REQUEST;
          case 2: return RESPONSE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final MessageType[] VALUES = {
        REQUEST, RESPONSE, 
      };
      
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protocol.protobuf.ProtoMessage.MessageType)
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // required .protocol.protobuf.ProtoMessage.Command command = 2;
    public static final int COMMAND_FIELD_NUMBER = 2;
    private br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command getCommand() {
      return command_;
    }
    
    // required .protocol.protobuf.ProtoMessage.MessageType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType getType() {
      return type_;
    }
    
    // required string srcId = 4;
    public static final int SRCID_FIELD_NUMBER = 4;
    private Object srcId_;
    public boolean hasSrcId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getSrcId() {
      Object ref = srcId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          srcId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSrcIdBytes() {
      Object ref = srcId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        srcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string dstId = 5;
    public static final int DSTID_FIELD_NUMBER = 5;
    private Object dstId_;
    public boolean hasDstId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getDstId() {
      Object ref = dstId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dstId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDstIdBytes() {
      Object ref = dstId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dstId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string argument = 6;
    public static final int ARGUMENT_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList argument_;
    public java.util.List<String>
        getArgumentList() {
      return argument_;
    }
    public int getArgumentCount() {
      return argument_.size();
    }
    public String getArgument(int index) {
      return argument_.get(index);
    }
    
    private void initFields() {
      id_ = 0L;
      command_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command.PING;
      type_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType.REQUEST;
      srcId_ = "";
      dstId_ = "";
      argument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSrcId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDstId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, command_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSrcIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDstIdBytes());
      }
      for (int i = 0; i < argument_.size(); i++) {
        output.writeBytes(6, argument_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, command_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSrcIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDstIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < argument_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(argument_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArgumentList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.internal_static_protocol_protobuf_ProtoMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.internal_static_protocol_protobuf_ProtoMessage_fieldAccessorTable;
      }
      
      // Construct using protocol.component.protobuf.MessageProtos.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command.PING;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType.REQUEST;
        bitField0_ = (bitField0_ & ~0x00000004);
        srcId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dstId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        argument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.getDescriptor();
      }
      
      public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage getDefaultInstanceForType() {
        return br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.getDefaultInstance();
      }
      
      public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage build() {
        br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage buildPartial() {
        br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage result = new br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.srcId_ = srcId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dstId_ = dstId_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          argument_ = new com.google.protobuf.UnmodifiableLazyStringList(
              argument_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.argument_ = argument_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage) {
          return mergeFrom((br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage other) {
        if (other == br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSrcId()) {
          setSrcId(other.getSrcId());
        }
        if (other.hasDstId()) {
          setDstId(other.getDstId());
        }
        if (!other.argument_.isEmpty()) {
          if (argument_.isEmpty()) {
            argument_ = other.argument_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureArgumentIsMutable();
            argument_.addAll(other.argument_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSrcId()) {
          
          return false;
        }
        if (!hasDstId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command value = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                command_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType value = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              srcId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              dstId_ = input.readBytes();
              break;
            }
            case 50: {
              ensureArgumentIsMutable();
              argument_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // required .protocol.protobuf.ProtoMessage.Command command = 2;
      private br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command command_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command.PING;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command getCommand() {
        return command_;
      }
      public Builder setCommand(br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Command.PING;
        onChanged();
        return this;
      }
      
      // required .protocol.protobuf.ProtoMessage.MessageType type = 3;
      private br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType type_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType.REQUEST;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType getType() {
        return type_;
      }
      public Builder setType(br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.MessageType.REQUEST;
        onChanged();
        return this;
      }
      
      // required string srcId = 4;
      private Object srcId_ = "";
      public boolean hasSrcId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getSrcId() {
        Object ref = srcId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          srcId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSrcId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        srcId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        srcId_ = getDefaultInstance().getSrcId();
        onChanged();
        return this;
      }
      void setSrcId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        srcId_ = value;
        onChanged();
      }
      
      // required string dstId = 5;
      private Object dstId_ = "";
      public boolean hasDstId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDstId() {
        Object ref = dstId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dstId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDstId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dstId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDstId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dstId_ = getDefaultInstance().getDstId();
        onChanged();
        return this;
      }
      void setDstId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        dstId_ = value;
        onChanged();
      }
      
      // repeated string argument = 6;
      private com.google.protobuf.LazyStringList argument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgumentIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          argument_ = new com.google.protobuf.LazyStringArrayList(argument_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<String>
          getArgumentList() {
        return java.util.Collections.unmodifiableList(argument_);
      }
      public int getArgumentCount() {
        return argument_.size();
      }
      public String getArgument(int index) {
        return argument_.get(index);
      }
      public Builder setArgument(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentIsMutable();
        argument_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addArgument(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentIsMutable();
        argument_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllArgument(
          java.lang.Iterable<String> values) {
        ensureArgumentIsMutable();
        super.addAll(values, argument_);
        onChanged();
        return this;
      }
      public Builder clearArgument() {
        argument_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      void addArgument(com.google.protobuf.ByteString value) {
        ensureArgumentIsMutable();
        argument_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.protobuf.ProtoMessage)
    }
    
    static {
      defaultInstance = new ProtoMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.protobuf.ProtoMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_protobuf_ProtoMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_protobuf_ProtoMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protomessage.proto\022\021protocol.protobuf\"" +
      "\250\002\n\014ProtoMessage\022\n\n\002id\030\001 \002(\003\0228\n\007command\030" +
      "\002 \002(\0162\'.protocol.protobuf.ProtoMessage.C" +
      "ommand\0229\n\004type\030\003 \002(\0162+.protocol.protobuf" +
      ".ProtoMessage.MessageType\022\r\n\005srcId\030\004 \002(\t" +
      "\022\r\n\005dstId\030\005 \002(\t\022\020\n\010argument\030\006 \003(\t\"=\n\007Com" +
      "mand\022\010\n\004PING\020\001\022\t\n\005STORE\020\002\022\r\n\tFIND_NODE\020\003" +
      "\022\016\n\nFIND_VALUE\020\004\"(\n\013MessageType\022\013\n\007REQUE" +
      "ST\020\001\022\014\n\010RESPONSE\020\002B,\n\033protocol.component" +
      ".protobufB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_protobuf_ProtoMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_protobuf_ProtoMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_protobuf_ProtoMessage_descriptor,
              new java.lang.String[] { "Id", "Command", "Type", "SrcId", "DstId", "Argument", },
              br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.class,
              br.biofoco.p2p.protocol.protobuf.MessageProtos.ProtoMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
