/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;  
@SuppressWarnings("all")
public enum Command { 
  SAVE_FILE, INFO, GET_FILE, RUN_TASK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Command\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"symbols\":[\"SAVE_FILE\",\"INFO\",\"GET_FILE\",\"RUN_TASK\"]}");
}
