/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;

@SuppressWarnings("all")
public interface PingPong {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"PingPong\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"types\":[],\"messages\":{\"ping\":{\"request\":[{\"name\":\"message\",\"type\":\"string\"}],\"response\":[\"string\"]}}}");
  java.lang.Object ping(java.lang.CharSequence message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends PingPong {
    public static final org.apache.avro.Protocol PROTOCOL = br.unb.cic.bionimbus.avro.proto.PingPong.PROTOCOL;
    void ping(java.lang.CharSequence message, org.apache.avro.ipc.Callback<java.lang.Object> callback) throws java.io.IOException;
  }
}