/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package br.unb.cic.bionimbus.avro.proto;  
@SuppressWarnings("all")
public class NodeState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NodeState\",\"namespace\":\"br.unb.cic.bionimbus.avro.proto\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"state\",\"type\":{\"type\":\"enum\",\"name\":\"State\",\"symbols\":[\"IDLE\",\"WORKING\",\"BUSY\"]}}]}");
  @Deprecated public long timestamp;
  @Deprecated public br.unb.cic.bionimbus.avro.proto.State state;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp;
    case 1: return state;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp = (java.lang.Long)value$; break;
    case 1: state = (br.unb.cic.bionimbus.avro.proto.State)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'state' field.
   */
  public br.unb.cic.bionimbus.avro.proto.State getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(br.unb.cic.bionimbus.avro.proto.State value) {
    this.state = value;
  }

  /** Creates a new NodeState RecordBuilder */
  public static br.unb.cic.bionimbus.avro.proto.NodeState.Builder newBuilder() {
    return new br.unb.cic.bionimbus.avro.proto.NodeState.Builder();
  }
  
  /** Creates a new NodeState RecordBuilder by copying an existing Builder */
  public static br.unb.cic.bionimbus.avro.proto.NodeState.Builder newBuilder(br.unb.cic.bionimbus.avro.proto.NodeState.Builder other) {
    return new br.unb.cic.bionimbus.avro.proto.NodeState.Builder(other);
  }
  
  /** Creates a new NodeState RecordBuilder by copying an existing NodeState instance */
  public static br.unb.cic.bionimbus.avro.proto.NodeState.Builder newBuilder(br.unb.cic.bionimbus.avro.proto.NodeState other) {
    return new br.unb.cic.bionimbus.avro.proto.NodeState.Builder(other);
  }
  
  /**
   * RecordBuilder for NodeState instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NodeState>
    implements org.apache.avro.data.RecordBuilder<NodeState> {

    private long timestamp;
    private br.unb.cic.bionimbus.avro.proto.State state;

    /** Creates a new Builder */
    private Builder() {
      super(br.unb.cic.bionimbus.avro.proto.NodeState.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(br.unb.cic.bionimbus.avro.proto.NodeState.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing NodeState instance */
    private Builder(br.unb.cic.bionimbus.avro.proto.NodeState other) {
            super(br.unb.cic.bionimbus.avro.proto.NodeState.SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = (java.lang.Long) data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.state)) {
        this.state = (br.unb.cic.bionimbus.avro.proto.State) data().deepCopy(fields()[1].schema(), other.state);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public br.unb.cic.bionimbus.avro.proto.NodeState.Builder setTimestamp(long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'timestamp' field */
    public br.unb.cic.bionimbus.avro.proto.NodeState.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'state' field */
    public br.unb.cic.bionimbus.avro.proto.State getState() {
      return state;
    }
    
    /** Sets the value of the 'state' field */
    public br.unb.cic.bionimbus.avro.proto.NodeState.Builder setState(br.unb.cic.bionimbus.avro.proto.State value) {
      validate(fields()[1], value);
      this.state = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'state' field has been set */
    public boolean hasState() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'state' field */
    public br.unb.cic.bionimbus.avro.proto.NodeState.Builder clearState() {
      state = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public NodeState build() {
      try {
        NodeState record = new NodeState();
        record.timestamp = fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.state = fieldSetFlags()[1] ? this.state : (br.unb.cic.bionimbus.avro.proto.State) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
